### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by cherrishccl** [gangan1345/wallet-eth-android#1]
您好，您上传的不是完整的APP吧，有完整的demo吗？

**Comment by gangan1345** [comment]
项目编译是没有问题的，Test类中main函数运行调试 wallet-eth模块，项目中没有放Activity等相关页面

**Comment by gangan1345** [comment]
在项目中 使用wallet-eth模块就好了， 根据自己的业务扩展， demo我就不整了。
